apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudwatch-agent.fullname" . }}
data:
  amazon-cloudwatch-agent.json: |
    {
      "agent": {
        "metrics_collection_interval": 60,
        "mode": "prometheus",
        "region": "{{ .Values.config.region }}"
      },
      "metrics": {
        "namespace": "litellm/Metrics",
        "metrics_collected": {
          "prometheus": {
            "prometheus_config_path": "/etc/prometheus/prometheus.yaml",
            "emf_processor": {
              "metric_declaration": [
                {
                  "source_labels": ["job"],
                  "label_matcher": ".*",
                  "dimensions": [["Service"]],
                  "metric_selectors": ["^.*$"]
                }
              ]
            },
            "measurement": [
              { "metric_name": "up", "unit": "Count" },
              { "metric_name": ".*", "unit": "None" }
            ]
          }
        },
        "force_flush_interval": 30
      }
    }

  prometheus.yaml: |
    global:
      scrape_interval: {{ .Values.config.scrapeInterval }}s
    scrape_configs:
      - job_name: '{{ .Values.config.targetService }}'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['{{ .Values.config.targetService }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.config.targetPort }}']
