apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudwatch-agent.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cloudwatch-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudwatch-agent.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: cloudwatch-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          # No args or command modifications, let it run defaults
          env:
            - name: AWS_REGION
              value: {{ .Values.config.region }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: env
                  key: AWS_SECRET_ACCESS_KEY
          volumeMounts:
            - name: cwagent-config
              mountPath: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
              subPath: amazon-cloudwatch-agent.json
            - name: prometheus-config
              mountPath: /etc/prometheus
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      volumes:
        - name: cwagent-config
          configMap:
            name: {{ include "cloudwatch-agent.fullname" . }}
            items:
              - key: amazon-cloudwatch-agent.json
                path: amazon-cloudwatch-agent.json
        - name: prometheus-config
          configMap:
            name: {{ include "cloudwatch-agent.fullname" . }}
            items:
              - key: prometheus.yaml
                path: prometheus.yaml
